[package]
name = "native_iroh_engine"
version = "0.1.0"
edition = "2021"

[lib]
name = "native_iroh_engine"
crate-type = ["cdylib"]

[dependencies]
iroh = { version = "1.1.0" }
tokio = { version = "1.38", features = ["rt-multi-thread", "sync", "macros", "time"] }
tokio-util = { version = "0.7" }
jni = "0.21.1"
futures-util = "0.3"
parking_lot = "0.12"
anyhow = "1.0"
iroh-blobs = "0.103.0"
iroh-tickets = "1.0.0"
